### ISSUE TITLE
Make classic installer (setup)

### ISSUE THREAD

**Issue by xmha97** [MarkHopper24/barcodrod.io#22]
Thanks for making this app and MSIX package.
But I want to install this app on a offline PC.
Please make classic installer (setup).
Thanks.

**Comment by MarkHopper24** [comment]
Hi, @xmha97, thanks for the request. The MSIX has the benefit of using the MSFT Store's code signing certificate. Since I don't plan on purchasing one for this project since it's FOSS, it would be difficult to offer a .MSI or .EXE setup installer available securely since it would be unsigned. 

So for now, I am going to mark this as not planned, but I will investigate ways to package the .MSIX differently so it contains all relevant dependency packages for offline installer scenarios. In the meantime, the code is available so feel free to build/modify locally for offline scenarios if you'd like.

**Comment by MarkHopper24** [comment]
Continuing in https://github.com/MarkHopper24/barcodrod.io/issues/25
